export const DUMMY_PAGINATED = {
  status: true,
  message: 'Success',
  timestamp: 1706020639291,
  data: {
    hotels: [
      {
        hotel_id: 1362336,
        accessibilityLabel:
          'Hotel Linkway.\n2 out of 5 stars.\n8.4 Very good 252 reviews.\n‎Khar‬ • ‎4.6 km from centre‬\n‎1.4 km from beach‬.\n Hotel room : Beds: 1 double or 2 singles.\n129 USD.\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          propertyClass: 2,
          position: 0,
          currency: 'INR',
          reviewScoreWord: 'Very good',
          countryCode: 'in',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/162282985.jpg?k=8442c7cc0bfdd20c0d7f92e11aa6dbf52e8b3836565582fb6514f212aa2778a8&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 0,
          isFirstPage: true,
          reviewCount: 252,
          reviewScore: 8.4,
          name: 'Hotel Linkway',
          rankingPosition: 0,
          ufi: -2092174,
          id: 1362336,
          checkout: {
            fromTime: '00:00',
            untilTime: '12:00',
          },
          mainPhotoId: 162282985,
          longitude: 72.8343397378922,
          checkin: {
            fromTime: '12:00',
            untilTime: '17:00',
          },
          accuratePropertyClass: 2,
          qualityClass: 0,
          priceBreakdown: {
            taxExceptions: [],
            grossPrice: {
              currency: 'USD',
              value: 129.438804331485,
            },
            benefitBadges: [],
          },
          checkoutDate: '2024-02-04',
          checkinDate: '2024-02-01',
          blockIds: ['136233601_142265761_0_0_0'],
          latitude: 19.0718236623439,
          isPreferred: true,
        },
      },
      {
        hotel_id: 4040493,
        accessibilityLabel:
          'Locomo Mumbai - Stay Work Eat.\n8.8 Fabulous 682 reviews.\n‎Western Suburbs‬ • ‎4.3 km from centre‬\n‎1.9 km from beach‬\n‎Travel Sustainable‬.\n Bed in dormitory : 1 bed.\nOriginal price 43 USD. Current price 38 USD..\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          propertyClass: 0,
          position: 1,
          currency: 'INR',
          reviewScoreWord: 'Fabulous',
          countryCode: 'in',
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/452657004.jpg?k=42500f35b1755c2eeb64838bdd62260f866f182a0417b5fd246cf20c87405bc9&o=',
          ],
          optOutFromGalleryChanges: 0,
          isFirstPage: true,
          reviewCount: 682,
          reviewScore: 8.8,
          name: 'Locomo Mumbai - Stay Work Eat',
          rankingPosition: 1,
          ufi: -2092174,
          id: 4040493,
          checkout: {
            fromTime: '00:00',
            untilTime: '12:00',
          },
          mainPhotoId: 452657004,
          longitude: 72.845075,
          accuratePropertyClass: 0,
          checkin: {
            untilTime: '00:00',
            fromTime: '14:00',
          },
          priceBreakdown: {
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                text: 'Mobile-only price',
                explanation: 'Mobile-only price',
                variant: 'constructive',
              },
            ],
            grossPrice: {
              value: 38.4073247189962,
              currency: 'USD',
            },
            strikethroughPrice: {
              currency: 'USD',
              value: 42.6747602992998,
            },
            taxExceptions: [],
          },
          qualityClass: 0,
          checkoutDate: '2024-02-04',
          checkinDate: '2024-02-01',
          blockIds: ['404049301_385004104_0_41_0'],
          latitude: 19.099626,
          isPreferred: true,
        },
      },
      {
        hotel_id: 5538606,
        accessibilityLabel:
          'AVIRAHI HOTEL.\n3 out of 5 for property rating.\n6.6 Pleasant 46 reviews.\n‎Western Suburbs‬ • ‎14 km from centre‬.\n Bed in dormitory : 1 bed.\n32 USD.\nIncludes taxes and charges.',
        property: {
          propertyClass: 0,
          position: 2,
          currency: 'INR',
          reviewScoreWord: 'Pleasant',
          countryCode: 'in',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/430485463.jpg?k=865f241244c6a9bc6e5ff195d84be3e2045352572b01c3d5d66d4df2c5f24871&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 0,
          isFirstPage: true,
          reviewScore: 6.6,
          reviewCount: 46,
          name: 'AVIRAHI HOTEL',
          ufi: -2092174,
          rankingPosition: 2,
          id: 5538606,
          checkout: {
            fromTime: '10:00',
            untilTime: '11:30',
          },
          mainPhotoId: 430485463,
          longitude: 72.8512505,
          accuratePropertyClass: 0,
          checkin: {
            untilTime: '12:00',
            fromTime: '11:00',
          },
          qualityClass: 3,
          priceBreakdown: {
            benefitBadges: [],
            grossPrice: {
              value: 32.3597010828711,
              currency: 'USD',
            },
            taxExceptions: [],
          },
          checkoutDate: '2024-02-04',
          blockIds: ['553860608_335392049_0_0_0'],
          checkinDate: '2024-02-01',
          latitude: 19.20317,
        },
      },
      {
        hotel_id: 7687912,
        accessibilityLabel:
          'Hotel Oyster Suite Andheri West.\n3 out of 5 stars.\n6.7 Pleasant 187 reviews.\n‎Western Suburbs‬ • ‎6 km from centre‬\n‎2.9 km from beach‬.\n Hotel room : 1 bed.\n97 USD.\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          optOutFromGalleryChanges: 0,
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/319285197.jpg?k=db121112c8549c02b5616ad588c67a215b61ace01223d7f7693f829b4dce0746&o=',
          ],
          name: 'Hotel Oyster Suite Andheri West',
          reviewCount: 187,
          reviewScore: 6.7,
          isFirstPage: true,
          currency: 'INR',
          position: 3,
          propertyClass: 3,
          countryCode: 'in',
          reviewScoreWord: 'Pleasant',
          latitude: 19.125383,
          blockIds: ['768791201_384251114_2_0_0'],
          checkinDate: '2024-02-01',
          checkoutDate: '2024-02-04',
          priceBreakdown: {
            taxExceptions: [],
            grossPrice: {
              currency: 'USD',
              value: 97.0791032486134,
            },
            benefitBadges: [],
          },
          qualityClass: 0,
          checkout: {
            fromTime: '00:00',
            untilTime: '11:00',
          },
          id: 7687912,
          ufi: -2092174,
          rankingPosition: 3,
          accuratePropertyClass: 3,
          checkin: {
            fromTime: '12:00',
            untilTime: '00:00',
          },
          longitude: 72.84709,
          mainPhotoId: 319285197,
        },
      },
      {
        hotel_id: 11251199,
        accessibilityLabel:
          'Hotel Rose Inn.\n3 out of 5 stars.\n7.1 Good 36 reviews.\n‎Western Suburbs‬ • ‎2.9 km from centre‬\n‎Travel Sustainable‬.\n1 bed.\nOriginal price 98 USD. Current price 74 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          checkoutDate: '2024-02-04',
          qualityClass: 0,
          priceBreakdown: {
            strikethroughPrice: {
              value: 98.2561873755028,
              currency: 'USD',
            },
            benefitBadges: [
              {
                text: 'Early 2024 Deal',
                variant: 'constructive',
                explanation: 'Early 2024 Deal',
                identifier: 'Early Year Deals',
              },
            ],
            grossPrice: {
              currency: 'USD',
              value: 73.692207947671,
            },
            taxExceptions: [],
          },
          latitude: 19.099907036214,
          blockIds: ['1125119901_385205145_1_42_0'],
          checkinDate: '2024-02-01',
          ufi: -2092174,
          rankingPosition: 4,
          id: 11251199,
          checkout: {
            untilTime: '11:00',
            fromTime: '10:30',
          },
          longitude: 72.888363554666,
          mainPhotoId: 514398062,
          accuratePropertyClass: 3,
          checkin: {
            fromTime: '11:30',
            untilTime: '23:00',
          },
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/514398062.jpg?k=ed1cd8c70eda158d590f1adef8a7525a2bc05c82c6634598fa633e95df715b77&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 1,
          isFirstPage: true,
          name: 'Hotel Rose Inn',
          reviewCount: 36,
          reviewScore: 7.1,
          propertyClass: 3,
          currency: 'INR',
          position: 4,
          countryCode: 'in',
          reviewScoreWord: 'Good',
        },
      },
      {
        hotel_id: 2357761,
        accessibilityLabel:
          'Hotel Flora Fountain,Fort.\n2 out of 5 stars.\n6.5 Pleasant 272 reviews.\n‎In city centre‬\n‎2.9 km from beach‬.\n1 bed.\nOriginal price 132 USD. Current price 119 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          isFirstPage: true,
          name: 'Hotel Flora Fountain,Fort',
          reviewCount: 272,
          reviewScore: 6.5,
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/98432289.jpg?k=6255aead856ea49990efc36e33a45111d4eb3e210ccb7e7236d15ff083eb41fe&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 0,
          countryCode: 'in',
          reviewScoreWord: 'Pleasant',
          propertyClass: 2,
          currency: 'INR',
          position: 5,
          checkoutDate: '2024-02-04',
          priceBreakdown: {
            strikethroughPrice: {
              currency: 'USD',
              value: 132.094996462037,
            },
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                text: 'Mobile-only price',
                explanation: 'Mobile-only price',
                variant: 'constructive',
              },
            ],
            grossPrice: {
              currency: 'USD',
              value: 118.885496815833,
            },
            taxExceptions: [],
          },
          qualityClass: 0,
          latitude: 18.9337874596375,
          checkinDate: '2024-02-01',
          blockIds: ['235776104_170722030_1_0_0'],
          longitude: 72.8330497315619,
          mainPhotoId: 98432289,
          accuratePropertyClass: 2,
          checkin: {
            fromTime: '12:00',
            untilTime: '00:00',
          },
          rankingPosition: 5,
          ufi: -2092174,
          id: 2357761,
          checkout: {
            untilTime: '11:00',
            fromTime: '00:00',
          },
        },
      },
      {
        hotel_id: 8778629,
        accessibilityLabel:
          'Hotel Ariana Residency.\n4 out of 5 stars.\n6.9 Pleasant 428 reviews.\n‎Western Suburbs‬ • ‎7 km from centre‬\n‎1.5 km from beach‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\nOriginal price 345 USD. Current price 213 USD..\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          checkout: {
            fromTime: '00:00',
            untilTime: '11:00',
          },
          ufi: -2092174,
          id: 8778629,
          rankingPosition: 6,
          checkin: {
            fromTime: '12:00',
            untilTime: '00:00',
          },
          accuratePropertyClass: 4,
          isPreferredPlus: true,
          mainPhotoId: 392019082,
          longitude: 72.8326159372177,
          checkinDate: '2024-02-01',
          blockIds: ['877862902_386352140_1_2_0'],
          latitude: 19.1275934612682,
          priceBreakdown: {
            grossPrice: {
              currency: 'USD',
              value: 212.940990494516,
            },
            benefitBadges: [
              {
                text: 'Early 2024 Deal',
                explanation: 'Early 2024 Deal',
                variant: 'constructive',
                identifier: 'Early Year Deals',
              },
            ],
            strikethroughPrice: {
              currency: 'USD',
              value: 345.151608390592,
            },
            taxExceptions: [],
          },
          qualityClass: 0,
          checkoutDate: '2024-02-04',
          isPreferred: true,
          position: 6,
          currency: 'INR',
          propertyClass: 4,
          reviewScoreWord: 'Pleasant',
          countryCode: 'in',
          optOutFromGalleryChanges: 0,
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/392019082.jpg?k=d825a25be93ddb1a2bc16e0fdb573ec8bcb9ed69e286890b207ca558748dca32&o=',
          ],
          reviewScore: 6.9,
          reviewCount: 428,
          name: 'Hotel Ariana Residency',
          isFirstPage: true,
        },
      },
      {
        hotel_id: 10765886,
        accessibilityLabel:
          'Locomo Express - Stay Work Eat.\n8.7 Fabulous 48 reviews.\n‎Santacruz‬ • ‎4.4 km from centre‬\n‎1.2 km from beach‬\n‎Travel Sustainable‬.\n Bed in dormitory : 1 bed.\n39 USD.\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          id: 10765886,
          ufi: -2092174,
          rankingPosition: 7,
          checkout: {
            untilTime: '12:00',
            fromTime: '12:00',
          },
          mainPhotoId: 504525797,
          longitude: 72.835814871164,
          checkin: {
            fromTime: '14:00',
            untilTime: '00:00',
          },
          accuratePropertyClass: 0,
          priceBreakdown: {
            benefitBadges: [],
            grossPrice: {
              currency: 'USD',
              value: 39.1611709221392,
            },
            taxExceptions: [],
          },
          qualityClass: 0,
          checkoutDate: '2024-02-04',
          checkinDate: '2024-02-01',
          blockIds: ['1076588601_385004219_0_1_0'],
          latitude: 19.076698965093,
          propertyClass: 0,
          position: 7,
          currency: 'INR',
          reviewScoreWord: 'Fabulous',
          countryCode: 'in',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/504525797.jpg?k=6b54dcb7462e7c36735c1498377b0d04a3c1783c6ed1562b3749398f5655b329&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 0,
          isFirstPage: true,
          reviewScore: 8.7,
          reviewCount: 48,
          name: 'Locomo Express - Stay Work Eat',
        },
      },
      {
        hotel_id: 3150148,
        accessibilityLabel:
          'Theory9 Premium Service Apartments Khar.\n4 out of 5 for property rating.\n8.2 Very good 132 reviews.\n‎Khar‬ • ‎4.3 km from centre‬\n‎2 km from beach‬\n‎Travel Sustainable‬.\n Private room : 1 bed.\nOriginal price 377 USD. Current price 274 USD..\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          checkout: {
            untilTime: '12:00',
            fromTime: '00:00',
          },
          id: 3150148,
          ufi: -2092174,
          rankingPosition: 8,
          accuratePropertyClass: 0,
          checkin: {
            untilTime: '00:00',
            fromTime: '14:00',
          },
          longitude: 72.837993,
          mainPhotoId: 205595337,
          latitude: 19.067258,
          checkinDate: '2024-02-01',
          blockIds: ['315014801_375589986_2_0_0'],
          checkoutDate: '2024-02-04',
          qualityClass: 4,
          priceBreakdown: {
            taxExceptions: [],
            benefitBadges: [
              {
                variant: 'constructive',
                explanation: 'Mobile-only price',
                text: 'Mobile-only price',
                identifier: 'Mobile Rate',
              },
            ],
            grossPrice: {
              currency: 'USD',
              value: 273.54464317878,
            },
            strikethroughPrice: {
              value: 376.730487488929,
              currency: 'USD',
            },
          },
          isPreferred: true,
          currency: 'INR',
          position: 8,
          propertyClass: 0,
          countryCode: 'in',
          reviewScoreWord: 'Very good',
          optOutFromGalleryChanges: 0,
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/205595337.jpg?k=471163c602eb5c4091fceaa46f0647e514c74fb49bea0ba898982a964db73f36&o=',
          ],
          wishlistName: 'Mumbai',
          name: 'Theory9 Premium Service Apartments Khar',
          reviewCount: 132,
          reviewScore: 8.2,
          isFirstPage: true,
        },
      },
      {
        hotel_id: 905709,
        accessibilityLabel:
          'Empire Hotel - Grant Road.\n2 out of 5 stars.\n8.1 Very good 368 reviews.\n‎In city centre‬\n‎850 m from beach‬.\n Hotel room : 1 bed.\nOriginal price 148 USD. Current price 133 USD..\nIncludes taxes and charges.',
        property: {
          latitude: 18.9621845610683,
          checkinDate: '2024-02-01',
          blockIds: ['90570901_93665257_1_0_0'],
          checkoutDate: '2024-02-04',
          priceBreakdown: {
            taxExceptions: [],
            strikethroughPrice: {
              currency: 'USD',
              value: 148.312599988069,
            },
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                variant: 'constructive',
                explanation: 'Mobile-only price',
                text: 'Mobile-only price',
              },
            ],
            grossPrice: {
              value: 133.481339989262,
              currency: 'USD',
            },
          },
          qualityClass: 0,
          isPreferred: true,
          checkout: {
            untilTime: '11:00',
            fromTime: '00:00',
          },
          rankingPosition: 9,
          ufi: -2092174,
          id: 905709,
          checkin: {
            untilTime: '00:00',
            fromTime: '12:00',
          },
          accuratePropertyClass: 2,
          longitude: 72.8162926878051,
          mainPhotoId: 43212916,
          optOutFromGalleryChanges: 0,
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/43212916.jpg?k=f1acaf6f91fe87c41a700a3e160d97746f6d08b2962b06b51a7ec0dc277ccfc3&o=',
          ],
          wishlistName: 'Mumbai',
          name: 'Empire Hotel - Grant Road',
          reviewCount: 368,
          reviewScore: 8.1,
          isFirstPage: true,
          currency: 'INR',
          position: 9,
          propertyClass: 2,
          countryCode: 'in',
          reviewScoreWord: 'Very good',
        },
      },
      {
        hotel_id: 6457804,
        accessibilityLabel:
          'Nap Manor Hostels.\n8.9 Fabulous 942 reviews.\n‎Santacruz‬ • ‎3.3 km from centre‬\n‎2.3 km from beach‬\n‎Travel Sustainable‬.\n Bed in dormitory : 1 bed.\nOriginal price 52 USD. Current price 47 USD..\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          blockIds: ['645780407_366329404_1_1_0'],
          checkinDate: '2024-02-01',
          latitude: 19.082214276014,
          priceBreakdown: {
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                text: 'Mobile-only price',
                explanation: 'Mobile-only price',
                variant: 'constructive',
              },
            ],
            grossPrice: {
              currency: 'USD',
              value: 46.5900144661515,
            },
            strikethroughPrice: {
              currency: 'USD',
              value: 51.766622814796,
            },
            taxExceptions: [],
          },
          qualityClass: 0,
          checkoutDate: '2024-02-04',
          isPreferred: true,
          checkout: {
            fromTime: '11:00',
            untilTime: '11:30',
          },
          ufi: -2092174,
          rankingPosition: 10,
          id: 6457804,
          checkin: {
            untilTime: '00:00',
            fromTime: '13:00',
          },
          accuratePropertyClass: 0,
          mainPhotoId: 255856201,
          longitude: 72.8473843619365,
          optOutFromGalleryChanges: 0,
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/255856201.jpg?k=8bb15fa49ee8c5aec944756bff390466021c3db5a7dd744a81fda2401cc33e30&o=',
          ],
          wishlistName: 'Mumbai',
          reviewCount: 942,
          reviewScore: 8.9,
          name: 'Nap Manor Hostels',
          isFirstPage: true,
          position: 10,
          currency: 'INR',
          propertyClass: 0,
          reviewScoreWord: 'Fabulous',
          countryCode: 'in',
        },
      },
      {
        hotel_id: 8778869,
        accessibilityLabel:
          'FabHotel Anam International.\n3 out of 5 stars.\n6.8 Pleasant 43 reviews.\n‎In city centre‬\n‎1.3 km from beach‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\nOriginal price 208 USD. Current price 131 USD..\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          qualityClass: 0,
          priceBreakdown: {
            grossPrice: {
              currency: 'USD',
              value: 130.831080470575,
            },
            benefitBadges: [
              {
                identifier: 'Early Year Deals',
                explanation: 'Early 2024 Deal',
                variant: 'constructive',
                text: 'Early 2024 Deal',
              },
            ],
            strikethroughPrice: {
              value: 207.668381699325,
              currency: 'USD',
            },
            taxExceptions: [],
          },
          checkoutDate: '2024-02-04',
          blockIds: ['877886904_386589350_1_2_0'],
          checkinDate: '2024-02-01',
          latitude: 18.9653607983147,
          isPreferred: true,
          ufi: -2092174,
          rankingPosition: 11,
          id: 8778869,
          checkout: {
            fromTime: '00:00',
            untilTime: '11:00',
          },
          mainPhotoId: 521642601,
          longitude: 72.8185409573364,
          accuratePropertyClass: 3,
          checkin: {
            untilTime: '00:00',
            fromTime: '12:00',
          },
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/521642601.jpg?k=86424b77af810b12439e216f68dd1c5f8b57935c2220e19c693b07c859d587cd&o=',
          ],
          optOutFromGalleryChanges: 1,
          isFirstPage: true,
          reviewScore: 6.8,
          reviewCount: 43,
          name: 'FabHotel Anam International',
          propertyClass: 3,
          position: 11,
          currency: 'INR',
          reviewScoreWord: 'Pleasant',
          countryCode: 'in',
        },
      },
      {
        hotel_id: 10662407,
        accessibilityLabel:
          'Country Inn & Suites By UMRB.\n3 out of 5 stars.\n6.8 Pleasant 30 reviews.\n‎Western Suburbs‬ • ‎7 km from centre‬\n‎1.9 km from beach‬\n‎Travel Sustainable‬.\n1 bed.\nOriginal price 385 USD. Current price 219 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          position: 12,
          currency: 'INR',
          propertyClass: 3,
          reviewScoreWord: 'Pleasant',
          countryCode: 'in',
          optOutFromGalleryChanges: 0,
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/487277404.jpg?k=5b925fe7e674cd230d1fe4940c942f7cee631a4c12a5c23c89793bded8ae43f9&o=',
          ],
          reviewScore: 6.8,
          reviewCount: 30,
          name: 'Country Inn & Suites By UMRB',
          isFirstPage: true,
          checkout: {
            untilTime: '11:00',
            fromTime: '11:00',
          },
          rankingPosition: 12,
          ufi: -2092174,
          id: 10662407,
          accuratePropertyClass: 3,
          checkin: {
            fromTime: '13:00',
            untilTime: '00:00',
          },
          mainPhotoId: 487277404,
          longitude: 72.8355902194172,
          checkinDate: '2024-02-01',
          blockIds: ['1066240702_382443057_2_1_0'],
          latitude: 19.1288026003175,
          priceBreakdown: {
            taxExceptions: [],
            strikethroughPrice: {
              currency: 'USD',
              value: 384.614553120767,
            },
            grossPrice: {
              value: 219.034726704684,
              currency: 'USD',
            },
            benefitBadges: [
              {
                text: 'Early 2024 Deal',
                explanation: 'Early 2024 Deal',
                variant: 'constructive',
                identifier: 'Early Year Deals',
              },
            ],
          },
          qualityClass: 0,
          checkoutDate: '2024-02-04',
          isPreferred: true,
        },
      },
      {
        hotel_id: 9171122,
        accessibilityLabel:
          'GoSolo Stays.\n9.1 Superb 195 reviews.\n‎Khar‬ • ‎5 km from centre‬\n‎700 m from beach‬\n‎Travel Sustainable‬.\n Bed in dormitory : 1 bed.\n49 USD.\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          checkoutDate: '2024-02-04',
          priceBreakdown: {
            benefitBadges: [],
            grossPrice: {
              currency: 'USD',
              value: 48.5395516243067,
            },
            taxExceptions: [],
          },
          qualityClass: 0,
          latitude: 19.07348,
          blockIds: ['917112201_369850989_0_1_0'],
          checkinDate: '2024-02-01',
          ufi: -2092174,
          rankingPosition: 13,
          id: 9171122,
          checkout: {
            fromTime: '00:00',
            untilTime: '11:00',
          },
          longitude: 72.826296,
          mainPhotoId: 428017382,
          checkin: {
            fromTime: '13:00',
            untilTime: '00:00',
          },
          accuratePropertyClass: 0,
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/428017382.jpg?k=1ebefe2279dd5eeb794ff4257b5fd3c37a3554604a5aa33e125a9bbb71cf68a1&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 0,
          isFirstPage: true,
          name: 'GoSolo Stays',
          reviewCount: 195,
          reviewScore: 9.1,
          propertyClass: 0,
          currency: 'INR',
          position: 13,
          countryCode: 'in',
          reviewScoreWord: 'Superb',
        },
      },
      {
        hotel_id: 10766577,
        accessibilityLabel:
          'LOTUS GRAND HOTEL MUMBAI.\n3 out of 5 for property rating.\n7.8 Good 42 reviews.\n‎Western Suburbs‬ • ‎3 km from centre‬\n‎Travel Sustainable‬.\n Private room : 1 bed.\nOriginal price 107 USD. Current price 96 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          reviewScore: 7.8,
          reviewCount: 42,
          name: 'LOTUS GRAND HOTEL MUMBAI',
          isFirstPage: true,
          optOutFromGalleryChanges: 0,
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/495973677.jpg?k=61762003172a2f70ff49e4320e0cfdf2c84e31f9cf32bdd5bbdd6ce7137bcfef&o=',
          ],
          reviewScoreWord: 'Good',
          countryCode: 'in',
          position: 14,
          currency: 'INR',
          propertyClass: 0,
          checkinDate: '2024-02-01',
          blockIds: ['1076657701_380254398_1_1_0'],
          latitude: 19.09903859249,
          priceBreakdown: {
            taxExceptions: [],
            grossPrice: {
              value: 96.0755480187808,
              currency: 'USD',
            },
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                variant: 'constructive',
                explanation: 'Mobile-only price',
                text: 'Mobile-only price',
              },
            ],
            strikethroughPrice: {
              currency: 'USD',
              value: 106.750608909756,
            },
          },
          qualityClass: 3,
          checkoutDate: '2024-02-04',
          accuratePropertyClass: 0,
          checkin: {
            fromTime: '12:00',
            untilTime: '23:30',
          },
          mainPhotoId: 495973677,
          longitude: 72.892070306089,
          checkout: {
            untilTime: '11:00',
            fromTime: '11:00',
          },
          ufi: -2092174,
          id: 10766577,
          rankingPosition: 14,
        },
      },
      {
        hotel_id: 7775051,
        accessibilityLabel:
          'Home2 Suites and Service Apartments, Mumbai Airport.\n3 out of 5 for property rating.\n7.8 Good 445 reviews.\n‎Santacruz‬ • ‎2.6 km from centre‬\n‎3 km from beach‬\n‎Travel Sustainable‬.\n Private apartment – 23 m² : 2 beds • 1 bedroom • 1 living room • 1 bathroom.\nOriginal price 222 USD. Current price 200 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          optOutFromGalleryChanges: 0,
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/346582348.jpg?k=b32ef861b5f93a81020e5088f586013de0a14433e425260880f37dc6a4becb4b&o=',
          ],
          wishlistName: 'Mumbai',
          name: 'Home2 Suites and Service Apartments, Mumbai Airport',
          reviewScore: 7.8,
          reviewCount: 445,
          isFirstPage: true,
          currency: 'INR',
          position: 15,
          propertyClass: 0,
          countryCode: 'in',
          reviewScoreWord: 'Good',
          latitude: 19.080777267915,
          blockIds: ['777505102_348804010_1_41_0'],
          checkinDate: '2024-02-01',
          checkoutDate: '2024-02-04',
          qualityClass: 3,
          priceBreakdown: {
            taxExceptions: [],
            strikethroughPrice: {
              currency: 'USD',
              value: 222.472944944739,
            },
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                explanation: 'Mobile-only price',
                variant: 'constructive',
                text: 'Mobile-only price',
              },
            ],
            grossPrice: {
              currency: 'USD',
              value: 200.225650450265,
            },
          },
          checkout: {
            untilTime: '11:00',
            fromTime: '00:00',
          },
          id: 7775051,
          ufi: -2092174,
          rankingPosition: 15,
          checkin: {
            untilTime: '00:00',
            fromTime: '14:00',
          },
          accuratePropertyClass: 0,
          longitude: 72.853702259525,
          mainPhotoId: 346582348,
        },
      },
      {
        hotel_id: 5603522,
        accessibilityLabel:
          'Royal Hometel Suites.\n3 out of 5 stars.\n7.6 Good 761 reviews.\n‎21 km from centre‬\n‎Travel Sustainable‬.\nOriginal price 268 USD. Current price 241 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          isFirstPage: true,
          reviewCount: 761,
          reviewScore: 7.6,
          name: 'Royal Hometel Suites',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/234812576.jpg?k=4306fabb463e954708c746133543bb59ec2294e6885a4f9e18555cd91abd8d24&o=',
          ],
          wishlistName: 'Mumbai',
          optOutFromGalleryChanges: 0,
          reviewScoreWord: 'Good',
          countryCode: 'in',
          propertyClass: 3,
          position: 16,
          currency: 'INR',
          isPreferred: true,
          qualityClass: 0,
          priceBreakdown: {
            strikethroughPrice: {
              value: 267.978774592527,
              currency: 'USD',
            },
            benefitBadges: [
              {
                text: 'Mobile-only price',
                explanation: 'Mobile-only price',
                variant: 'constructive',
                identifier: 'Mobile Rate',
              },
            ],
            grossPrice: {
              currency: 'USD',
              value: 241.180897133274,
            },
            taxExceptions: [],
          },
          checkoutDate: '2024-02-04',
          blockIds: ['560352207_351045835_1_42_0'],
          checkinDate: '2024-02-01',
          latitude: 19.2631,
          mainPhotoId: 234812576,
          longitude: 72.874775,
          checkin: {
            untilTime: '00:00',
            fromTime: '14:00',
          },
          accuratePropertyClass: 3,
          rankingPosition: 16,
          ufi: -2092174,
          id: 5603522,
          checkout: {
            fromTime: '00:00',
            untilTime: '12:00',
          },
        },
      },
      {
        hotel_id: 328553,
        accessibilityLabel:
          'Hotel Suba Galaxy Mumbai.\n3 out of 5 stars.\n7.9 Good 496 reviews.\n‎Western Suburbs‬ • ‎5 km from centre‬\n‎Travel Sustainable‬.\n Hotel room : Beds: 1 double or 2 singles.\nOriginal price 264 USD. Current price 237 USD..\nIncludes taxes and charges.',
        property: {
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/63526409.jpg?k=b092fdaac137ef6660f2401a95724052c75fe0e6ce1af73020e1fc2af5cad711&o=',
          ],
          optOutFromGalleryChanges: 0,
          isFirstPage: true,
          name: 'Hotel Suba Galaxy Mumbai',
          reviewScore: 7.9,
          reviewCount: 496,
          propertyClass: 3,
          currency: 'INR',
          position: 17,
          countryCode: 'in',
          reviewScoreWord: 'Good',
          checkoutDate: '2024-02-04',
          priceBreakdown: {
            taxExceptions: [],
            strikethroughPrice: {
              currency: 'USD',
              value: 263.866395913245,
            },
            benefitBadges: [
              {
                identifier: 'Mobile Rate',
                text: 'Mobile-only price',
                variant: 'constructive',
                explanation: 'Mobile-only price',
              },
            ],
            grossPrice: {
              value: 237.47975632192,
              currency: 'USD',
            },
          },
          qualityClass: 0,
          latitude: 19.1140875054685,
          blockIds: ['32855301_368844728_1_41_0'],
          checkinDate: '2024-02-01',
          isPreferred: true,
          id: 328553,
          ufi: -2092174,
          rankingPosition: 17,
          checkout: {
            untilTime: '12:00',
            fromTime: '00:00',
          },
          longitude: 72.8519350290298,
          mainPhotoId: 63526409,
          checkin: {
            fromTime: '14:00',
            untilTime: '00:00',
          },
          accuratePropertyClass: 3,
        },
      },
      {
        hotel_id: 11321457,
        accessibilityLabel:
          'The Majlis Hotel - Near Taj Hotel Colaba Mumbai.\n3 out of 5 stars.\n4.7 Disappointing 6 reviews.\n‎Colaba‬ • ‎18 km from centre‬.\n2 beds.\nOriginal price 202 USD. Current price 131 USD..\nIncludes taxes and charges.\nFree cancellation.\nNo prepayment needed.',
        property: {
          reviewScoreWord: 'Disappointing',
          countryCode: 'in',
          position: 18,
          currency: 'INR',
          propertyClass: 3,
          reviewScore: 4.7,
          reviewCount: 6,
          name: 'The Majlis Hotel - Near Taj Hotel Colaba Mumbai',
          isFirstPage: true,
          optOutFromGalleryChanges: 0,
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/517620618.jpg?k=0b32437435eadca3b568da9908bfb3092597eba506ce2eb5c8e30682b95baa20&o=',
          ],
          accuratePropertyClass: 3,
          checkin: {
            fromTime: '12:00',
            untilTime: '00:00',
          },
          mainPhotoId: 517620618,
          longitude: 72.831544863539,
          checkout: {
            fromTime: '00:00',
            untilTime: '11:00',
          },
          ufi: -2092174,
          id: 11321457,
          rankingPosition: 18,
          blockIds: ['1132145706_385948338_2_0_0'],
          checkinDate: '2024-02-01',
          latitude: 18.918110933129,
          qualityClass: 0,
          priceBreakdown: {
            benefitBadges: [],
            grossPrice: {
              value: 131.461285649164,
              currency: 'USD',
            },
            strikethroughPrice: {
              value: 202.248131767944,
              currency: 'USD',
            },
            taxExceptions: [],
          },
          checkoutDate: '2024-02-04',
        },
      },
      {
        hotel_id: 10738796,
        accessibilityLabel:
          'FabExpress Bindra Elite.\n3 out of 5 stars.\n6.8 Pleasant 20 reviews.\n‎Western Suburbs‬ • ‎6 km from centre‬.\n Hotel room : 1 bed.\nOriginal price 119 USD. Current price 68 USD..\nIncludes taxes and charges.\nFree cancellation.',
        property: {
          currency: 'INR',
          position: 19,
          propertyClass: 3,
          countryCode: 'in',
          reviewScoreWord: 'Pleasant',
          optOutFromGalleryChanges: 1,
          wishlistName: 'Mumbai',
          photoUrls: [
            'https://cf.bstatic.com/xdata/images/hotel/square60/515221779.jpg?k=905fb0f5315d2a2e8f37504a9d3b0a4b67a5a2b1407593ef57564ef361511ce3&o=',
          ],
          name: 'FabExpress Bindra Elite',
          reviewScore: 6.8,
          reviewCount: 20,
          isFirstPage: true,
          checkout: {
            fromTime: '00:00',
            untilTime: '11:00',
          },
          id: 10738796,
          ufi: -2092174,
          rankingPosition: 19,
          checkin: {
            fromTime: '12:00',
            untilTime: '00:00',
          },
          accuratePropertyClass: 3,
          longitude: 72.864533,
          mainPhotoId: 515221779,
          latitude: 19.124386,
          checkinDate: '2024-02-01',
          blockIds: ['1073879604_385552004_1_1_0'],
          checkoutDate: '2024-02-04',
          priceBreakdown: {
            taxExceptions: [],
            strikethroughPrice: {
              value: 118.67920372143,
              currency: 'USD',
            },
            grossPrice: {
              value: 67.647146121215,
              currency: 'USD',
            },
            benefitBadges: [
              {
                identifier: 'Early Year Deals',
                text: 'Early 2024 Deal',
                explanation: 'Early 2024 Deal',
                variant: 'constructive',
              },
            ],
          },
          qualityClass: 0,
        },
      },
    ],
    meta: [
      {
        title: '841 properties',
      },
    ],
    appear: [
      {
        id: 'cma',
        component: {
          props: {
            fill: true,
            content: {
              props: {
                items: [
                  {
                    props: {
                      component: {
                        props: {
                          items: [
                            {
                              props: {
                                text: [
                                  {
                                    font: 'body_2',
                                    text: "Commission paid and other benefits may affect an accommodation's ranking.",
                                  },
                                  {
                                    color: 'foreground',
                                    font: 'strong_2',
                                    text: '  ',
                                  },
                                  {
                                    linkActions: [
                                      {
                                        props: {
                                          url: 'booking://webview?url=https%3A%2F%2Fm.booking.com%2Fgeneral.en.html%3Faid%3D332731%3Btmpl%3Ddocs%2Fterms-and-conditions',
                                        },
                                      },
                                    ],
                                    color: 'action_foreground',
                                    font: 'body_2',
                                    text: 'Find out more',
                                  },
                                ],
                              },
                            },
                          ],
                          spacing: 'spacing_half',
                        },
                      },
                    },
                  },
                  {
                    props: {},
                  },
                  {
                    props: {
                      component: {
                        props: {
                          icon: 'close',
                          tertiaryTintedColor: 'foreground',
                          variant: 'tertiary_tinted',
                          accessibilityLabel: 'Close',
                        },
                      },
                    },
                  },
                ],
                fitContentWidth: true,
              },
            },
          },
        },
      },
      {
        contentUrl:
          'https://mobile-apps.booking.com/json/mobile.saba?route_path=saba-chat-entrypoint&add_bh_info=1&add_genius_percentage_value=1&add_ribbon_text=1&affiliate_id=332731&arrival_date=2024-02-01&autoextend=1&booked_x_times_for_dates=1&booked_x_times_threshold=1&categories_filter_additional_data=&change_popularity_sort_option_copy_tag=1&change_sort_options_copy_tags=1&check_excluded_charge_or_tax=1&check_flexible_dates=1&check_is_candidate_wholesaler=1&currency_code=USD&dark_mode=1&deeplink_sec_since_click=168567.9046729803&departure_date=2024-02-04&dest_ids=-2092174&device_id=57d11ec8bad14e119e4c15a86202c23f&distance_unit=metric&dl_sr_adoption=1&dotd=2&exposure_api_version=2.17&fix_dotd=1&flex_window=0&generate_map_bounding_box=1&get_cny_campaign_banner=1&get_skiing_info=1&guest_qty=1&include_amazon_banner=1&include_apartment_config=1&include_badges_in_price_breakdown=1&include_beach_information=1&include_bh_quality_classification=1&include_block_ids=1&include_bsb_info=1&include_bwallet_hotel_eligibility=1&include_composite_breakdown=1&include_cpc_non_trader_copy=1&include_excluded_charges_detail=1&include_free_cancellation=1&include_genius_badge=1&include_last_reservation=1&include_nr_bookings_best_range_message=1&include_nr_bookings_today=1&include_offered_bed_types=1&include_preview_cards=1&include_rack_rate_savings=1&include_rtb=1&include_ski_information=1&languagecode=en&location_source=recents&mark_first_highlighted_hotel=1&min_saba_version=31&network_type=wifi&new_segments_carousel=1&offset=0&optimized_call=1&outcome=search_results&page_define_enabled=1&pref_match=0&reason=change_sort_options&remove_wishlist_padding=1&room_qty=1&rows=auto&saba=1&saba_payload_root=1&saba_version=50&sb_calendar_open=1&search_type=city&send_ranking_version=1&send_search_id=1&show_beach_filter_badge=1&show_city_distance=1&show_distance_to_beach=1&show_distance_to_nearest_public_transport=1&show_genius_free_breakfast=0&show_if_mobile_deal=1&show_negotiated_rates=1&show_no_prepayment=1&show_policy=1&show_review_score_breakdowns=1&show_selected_filter_values=1&show_soldout=1&sort_by=auto&sort_by_source=sort_options&sort_genius_new_copy=1&source=search_results&temperature_unit=c&travel_purpose=&unfiltered_count_enabled=1&units=metric&use_dest_based_list_creation=1&use_direct_payment=1&user_os=15.5&user_version=36.8-iphone&categories_filter=price%3A%3AUSD-min-max&page=search-results',
      },
      {
        id: 'banner_qualityrating',
        component: {
          props: {
            text: "Properties with these icons have been awarded Booking.com's quality rating for homes",
            title: '',
          },
        },
      },
      {
        id: 'signin_now',
        component: {
          props: {
            text: 'Get instant access to our Genius loyalty programme and enjoy discounts at properties worldwide.',
            title: 'Sign in and save money',
          },
        },
      },
    ],
  },
};
