import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';
import { cn } from '../lib/utils';
import QueryProvider from '@/lib/QueryProvider';

export const fontSans = Quicksand({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased bg-hero-img bg-center bg-no-repeat bg-cover',
          fontSans.variable
        )}
      >
        <QueryProvider>
          <>
            {children}
            <Toaster />
          </>
        </QueryProvider>
      </body>
    </html>
  );
}
